### ISSUE TITLE
Assertion crash

### ISSUE THREAD

**Issue by saleyn** [HdrHistogram/hdr_histogram_erl#4]
Below check should be handled gracefully as an exception:

``` erlang
1> f(R), {ok, R} = hdr_histogram:open(10, 1).
2> hdr_histogram:record(R, 100).
beam.smp: c_src/hdr_histogram.c:54: counts_index: Assertion `bucket_index < h->bucket_count' failed.
Aborted (core dumped)
```

**Comment by darach** [comment]
Hi Serge,

Ouch. I'll fix this weekend. Thanks for submitting the issue!

Cheers,

Darach.

**Comment by mikeb01** [comment]
This is a bug in the C code, which I fixed.  See: https://github.com/HdrHistogram/HdrHistogram_c/issues/6

**Comment by darach** [comment]
Thanks Mike! I hope to have a spare/free weekend soon so I can move on top of HdrHistogram_c now that it's a separate project.

**Comment by mikeb01** [comment]
There is an API change for the iterators in the latest version, ping me if you need any help.

**Comment by darach** [comment]
Hi Serge,

Patched and a defensive check added to make sure recorded values are in the specified range.
Without the check the underlying histogram can actually store values slightly wider than desired
due to how the underlying bucketing works.

Heinz Gies has contributed some EQC tests so we'll quickly find any outliers and mop up as we
add more random stochastic tests.

https://github.com/HdrHistogram/hdr_histogram_erl/blob/master/test/hdr_histogram_SUITE.erl#L285-L291

Thanks for reporting the issue!

Cheers,

Darach.

**Comment by saleyn** [comment]
Great, thanks!
